/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Numerator_H
#define Numerator_H

#include <thrift/TDispatchProcessor.h>
#include "numerator_types.h"

namespace numerator {

class NumeratorIf {
 public:
  virtual ~NumeratorIf() {}
  virtual void ping() = 0;
  virtual void query(Query& _return, const Query& request) = 0;
  virtual void disable_s2i() = 0;
  virtual void enable_s2i() = 0;
};

class NumeratorIfFactory {
 public:
  typedef NumeratorIf Handler;

  virtual ~NumeratorIfFactory() {}

  virtual NumeratorIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(NumeratorIf* /* handler */) = 0;
};

class NumeratorIfSingletonFactory : virtual public NumeratorIfFactory {
 public:
  NumeratorIfSingletonFactory(const boost::shared_ptr<NumeratorIf>& iface) : iface_(iface) {}
  virtual ~NumeratorIfSingletonFactory() {}

  virtual NumeratorIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(NumeratorIf* /* handler */) {}

 protected:
  boost::shared_ptr<NumeratorIf> iface_;
};

class NumeratorNull : virtual public NumeratorIf {
 public:
  virtual ~NumeratorNull() {}
  void ping() {
    return;
  }
  void query(Query& /* _return */, const Query& /* request */) {
    return;
  }
  void disable_s2i() {
    return;
  }
  void enable_s2i() {
    return;
  }
};


class Numerator_ping_args {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};

  Numerator_ping_args(const Numerator_ping_args&);
  Numerator_ping_args& operator=(const Numerator_ping_args&);
  Numerator_ping_args() {
  }

  virtual ~Numerator_ping_args() throw();

  bool operator == (const Numerator_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Numerator_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Numerator_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Numerator_ping_args& obj);
};


class Numerator_ping_pargs {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};


  virtual ~Numerator_ping_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Numerator_ping_pargs& obj);
};


class Numerator_ping_result {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};

  Numerator_ping_result(const Numerator_ping_result&);
  Numerator_ping_result& operator=(const Numerator_ping_result&);
  Numerator_ping_result() {
  }

  virtual ~Numerator_ping_result() throw();

  bool operator == (const Numerator_ping_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Numerator_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Numerator_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Numerator_ping_result& obj);
};


class Numerator_ping_presult {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};


  virtual ~Numerator_ping_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const Numerator_ping_presult& obj);
};

typedef struct _Numerator_query_args__isset {
  _Numerator_query_args__isset() : request(false) {}
  bool request :1;
} _Numerator_query_args__isset;

class Numerator_query_args {
 public:

  static const char* ascii_fingerprint; // = "B9E61830A79F059D4B6ECE6CD19BD044";
  static const uint8_t binary_fingerprint[16]; // = {0xB9,0xE6,0x18,0x30,0xA7,0x9F,0x05,0x9D,0x4B,0x6E,0xCE,0x6C,0xD1,0x9B,0xD0,0x44};

  Numerator_query_args(const Numerator_query_args&);
  Numerator_query_args& operator=(const Numerator_query_args&);
  Numerator_query_args() {
  }

  virtual ~Numerator_query_args() throw();
  Query request;

  _Numerator_query_args__isset __isset;

  void __set_request(const Query& val);

  bool operator == (const Numerator_query_args & rhs) const
  {
    if (!(request == rhs.request))
      return false;
    return true;
  }
  bool operator != (const Numerator_query_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Numerator_query_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Numerator_query_args& obj);
};


class Numerator_query_pargs {
 public:

  static const char* ascii_fingerprint; // = "B9E61830A79F059D4B6ECE6CD19BD044";
  static const uint8_t binary_fingerprint[16]; // = {0xB9,0xE6,0x18,0x30,0xA7,0x9F,0x05,0x9D,0x4B,0x6E,0xCE,0x6C,0xD1,0x9B,0xD0,0x44};


  virtual ~Numerator_query_pargs() throw();
  const Query* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Numerator_query_pargs& obj);
};

typedef struct _Numerator_query_result__isset {
  _Numerator_query_result__isset() : success(false), exc(false) {}
  bool success :1;
  bool exc :1;
} _Numerator_query_result__isset;

class Numerator_query_result {
 public:

  static const char* ascii_fingerprint; // = "35298038BCBA0F78DA5488140143BDA5";
  static const uint8_t binary_fingerprint[16]; // = {0x35,0x29,0x80,0x38,0xBC,0xBA,0x0F,0x78,0xDA,0x54,0x88,0x14,0x01,0x43,0xBD,0xA5};

  Numerator_query_result(const Numerator_query_result&);
  Numerator_query_result& operator=(const Numerator_query_result&);
  Numerator_query_result() {
  }

  virtual ~Numerator_query_result() throw();
  Query success;
  NumeratorException exc;

  _Numerator_query_result__isset __isset;

  void __set_success(const Query& val);

  void __set_exc(const NumeratorException& val);

  bool operator == (const Numerator_query_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(exc == rhs.exc))
      return false;
    return true;
  }
  bool operator != (const Numerator_query_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Numerator_query_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Numerator_query_result& obj);
};

typedef struct _Numerator_query_presult__isset {
  _Numerator_query_presult__isset() : success(false), exc(false) {}
  bool success :1;
  bool exc :1;
} _Numerator_query_presult__isset;

class Numerator_query_presult {
 public:

  static const char* ascii_fingerprint; // = "35298038BCBA0F78DA5488140143BDA5";
  static const uint8_t binary_fingerprint[16]; // = {0x35,0x29,0x80,0x38,0xBC,0xBA,0x0F,0x78,0xDA,0x54,0x88,0x14,0x01,0x43,0xBD,0xA5};


  virtual ~Numerator_query_presult() throw();
  Query* success;
  NumeratorException exc;

  _Numerator_query_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const Numerator_query_presult& obj);
};


class Numerator_disable_s2i_args {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};

  Numerator_disable_s2i_args(const Numerator_disable_s2i_args&);
  Numerator_disable_s2i_args& operator=(const Numerator_disable_s2i_args&);
  Numerator_disable_s2i_args() {
  }

  virtual ~Numerator_disable_s2i_args() throw();

  bool operator == (const Numerator_disable_s2i_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Numerator_disable_s2i_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Numerator_disable_s2i_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Numerator_disable_s2i_args& obj);
};


class Numerator_disable_s2i_pargs {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};


  virtual ~Numerator_disable_s2i_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Numerator_disable_s2i_pargs& obj);
};


class Numerator_disable_s2i_result {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};

  Numerator_disable_s2i_result(const Numerator_disable_s2i_result&);
  Numerator_disable_s2i_result& operator=(const Numerator_disable_s2i_result&);
  Numerator_disable_s2i_result() {
  }

  virtual ~Numerator_disable_s2i_result() throw();

  bool operator == (const Numerator_disable_s2i_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Numerator_disable_s2i_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Numerator_disable_s2i_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Numerator_disable_s2i_result& obj);
};


class Numerator_disable_s2i_presult {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};


  virtual ~Numerator_disable_s2i_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const Numerator_disable_s2i_presult& obj);
};


class Numerator_enable_s2i_args {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};

  Numerator_enable_s2i_args(const Numerator_enable_s2i_args&);
  Numerator_enable_s2i_args& operator=(const Numerator_enable_s2i_args&);
  Numerator_enable_s2i_args() {
  }

  virtual ~Numerator_enable_s2i_args() throw();

  bool operator == (const Numerator_enable_s2i_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Numerator_enable_s2i_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Numerator_enable_s2i_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Numerator_enable_s2i_args& obj);
};


class Numerator_enable_s2i_pargs {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};


  virtual ~Numerator_enable_s2i_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Numerator_enable_s2i_pargs& obj);
};


class Numerator_enable_s2i_result {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};

  Numerator_enable_s2i_result(const Numerator_enable_s2i_result&);
  Numerator_enable_s2i_result& operator=(const Numerator_enable_s2i_result&);
  Numerator_enable_s2i_result() {
  }

  virtual ~Numerator_enable_s2i_result() throw();

  bool operator == (const Numerator_enable_s2i_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Numerator_enable_s2i_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Numerator_enable_s2i_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Numerator_enable_s2i_result& obj);
};


class Numerator_enable_s2i_presult {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};


  virtual ~Numerator_enable_s2i_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const Numerator_enable_s2i_presult& obj);
};

class NumeratorClient : virtual public NumeratorIf {
 public:
  NumeratorClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  NumeratorClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  void send_ping();
  void recv_ping();
  void query(Query& _return, const Query& request);
  void send_query(const Query& request);
  void recv_query(Query& _return);
  void disable_s2i();
  void send_disable_s2i();
  void recv_disable_s2i();
  void enable_s2i();
  void send_enable_s2i();
  void recv_enable_s2i();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class NumeratorProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<NumeratorIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (NumeratorProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_query(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_disable_s2i(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_enable_s2i(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  NumeratorProcessor(boost::shared_ptr<NumeratorIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &NumeratorProcessor::process_ping;
    processMap_["query"] = &NumeratorProcessor::process_query;
    processMap_["disable_s2i"] = &NumeratorProcessor::process_disable_s2i;
    processMap_["enable_s2i"] = &NumeratorProcessor::process_enable_s2i;
  }

  virtual ~NumeratorProcessor() {}
};

class NumeratorProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  NumeratorProcessorFactory(const ::boost::shared_ptr< NumeratorIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< NumeratorIfFactory > handlerFactory_;
};

class NumeratorMultiface : virtual public NumeratorIf {
 public:
  NumeratorMultiface(std::vector<boost::shared_ptr<NumeratorIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~NumeratorMultiface() {}
 protected:
  std::vector<boost::shared_ptr<NumeratorIf> > ifaces_;
  NumeratorMultiface() {}
  void add(boost::shared_ptr<NumeratorIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    ifaces_[i]->ping();
  }

  void query(Query& _return, const Query& request) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->query(_return, request);
    }
    ifaces_[i]->query(_return, request);
    return;
  }

  void disable_s2i() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->disable_s2i();
    }
    ifaces_[i]->disable_s2i();
  }

  void enable_s2i() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->enable_s2i();
    }
    ifaces_[i]->enable_s2i();
  }

};

} // namespace

#endif
