/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef numerator_TYPES_H
#define numerator_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>



namespace numerator {

struct Operation {
  enum type {
    STR2ID = 1,
    ID2STR = 2
  };
};

extern const std::map<int, const char*> _Operation_VALUES_TO_NAMES;

typedef int64_t NumID;

typedef int32_t FailureIdx;

typedef struct _Query__isset {
  _Query__isset() : strings(false), ids(false), failures(false) {}
  bool strings;
  bool ids;
  bool failures;
} _Query__isset;

class Query {
 public:

  static const char* ascii_fingerprint; // = "D478EE81C1C8AB0A3FEC2FF77EFAFD1F";
  static const uint8_t binary_fingerprint[16]; // = {0xD4,0x78,0xEE,0x81,0xC1,0xC8,0xAB,0x0A,0x3F,0xEC,0x2F,0xF7,0x7E,0xFA,0xFD,0x1F};

  Query() : op((Operation::type)0) {
  }

  virtual ~Query() throw() {}

  Operation::type op;
  std::vector<std::string>  strings;
  std::vector<NumID>  ids;
  std::vector<FailureIdx>  failures;

  _Query__isset __isset;

  void __set_op(const Operation::type val) {
    op = val;
  }

  void __set_strings(const std::vector<std::string> & val) {
    strings = val;
  }

  void __set_ids(const std::vector<NumID> & val) {
    ids = val;
  }

  void __set_failures(const std::vector<FailureIdx> & val) {
    failures = val;
  }

  bool operator == (const Query & rhs) const
  {
    if (!(op == rhs.op))
      return false;
    if (!(strings == rhs.strings))
      return false;
    if (!(ids == rhs.ids))
      return false;
    if (!(failures == rhs.failures))
      return false;
    return true;
  }
  bool operator != (const Query &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Query & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(Query &a, Query &b);

} // namespace

#endif
