/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef numerator_CONSTANTS_H
#define numerator_CONSTANTS_H

#include "numerator_types.h"

namespace numerator {

class numeratorConstants {
 public:
  numeratorConstants();

};

extern const numeratorConstants g_numerator_constants;

} // namespace

#endif
