// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Numerator.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::numerator;

class NumeratorHandler : virtual public NumeratorIf {
 public:
  NumeratorHandler() {
    // Your initialization goes here
  }

  void ping() {
    // Your implementation goes here
    printf("ping\n");
  }

  void query(Query& _return, const Query& request) {
    // Your implementation goes here
    printf("query\n");
  }

  void disable_s2i() {
    // Your implementation goes here
    printf("disable_s2i\n");
  }

  void enable_s2i() {
    // Your implementation goes here
    printf("enable_s2i\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<NumeratorHandler> handler(new NumeratorHandler());
  shared_ptr<TProcessor> processor(new NumeratorProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

