/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Numerator_H
#define Numerator_H

#include <thrift/TDispatchProcessor.h>
#include "numerator_types.h"

namespace numerator {

class NumeratorIf {
 public:
  virtual ~NumeratorIf() {}
  virtual void ping() = 0;
  virtual void query(Query& _return, const Query& request) = 0;
};

class NumeratorIfFactory {
 public:
  typedef NumeratorIf Handler;

  virtual ~NumeratorIfFactory() {}

  virtual NumeratorIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(NumeratorIf* /* handler */) = 0;
};

class NumeratorIfSingletonFactory : virtual public NumeratorIfFactory {
 public:
  NumeratorIfSingletonFactory(const boost::shared_ptr<NumeratorIf>& iface) : iface_(iface) {}
  virtual ~NumeratorIfSingletonFactory() {}

  virtual NumeratorIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(NumeratorIf* /* handler */) {}

 protected:
  boost::shared_ptr<NumeratorIf> iface_;
};

class NumeratorNull : virtual public NumeratorIf {
 public:
  virtual ~NumeratorNull() {}
  void ping() {
    return;
  }
  void query(Query& /* _return */, const Query& /* request */) {
    return;
  }
};


class Numerator_ping_args {
 public:

  Numerator_ping_args() {
  }

  virtual ~Numerator_ping_args() throw() {}


  bool operator == (const Numerator_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Numerator_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Numerator_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Numerator_ping_pargs {
 public:


  virtual ~Numerator_ping_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Numerator_ping_result {
 public:

  Numerator_ping_result() {
  }

  virtual ~Numerator_ping_result() throw() {}


  bool operator == (const Numerator_ping_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Numerator_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Numerator_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Numerator_ping_presult {
 public:


  virtual ~Numerator_ping_presult() throw() {}


  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Numerator_query_args__isset {
  _Numerator_query_args__isset() : request(false) {}
  bool request;
} _Numerator_query_args__isset;

class Numerator_query_args {
 public:

  Numerator_query_args() {
  }

  virtual ~Numerator_query_args() throw() {}

  Query request;

  _Numerator_query_args__isset __isset;

  void __set_request(const Query& val) {
    request = val;
  }

  bool operator == (const Numerator_query_args & rhs) const
  {
    if (!(request == rhs.request))
      return false;
    return true;
  }
  bool operator != (const Numerator_query_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Numerator_query_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Numerator_query_pargs {
 public:


  virtual ~Numerator_query_pargs() throw() {}

  const Query* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Numerator_query_result__isset {
  _Numerator_query_result__isset() : success(false), exc(false) {}
  bool success;
  bool exc;
} _Numerator_query_result__isset;

class Numerator_query_result {
 public:

  Numerator_query_result() {
  }

  virtual ~Numerator_query_result() throw() {}

  Query success;
  NumeratorException exc;

  _Numerator_query_result__isset __isset;

  void __set_success(const Query& val) {
    success = val;
  }

  void __set_exc(const NumeratorException& val) {
    exc = val;
  }

  bool operator == (const Numerator_query_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(exc == rhs.exc))
      return false;
    return true;
  }
  bool operator != (const Numerator_query_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Numerator_query_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Numerator_query_presult__isset {
  _Numerator_query_presult__isset() : success(false), exc(false) {}
  bool success;
  bool exc;
} _Numerator_query_presult__isset;

class Numerator_query_presult {
 public:


  virtual ~Numerator_query_presult() throw() {}

  Query* success;
  NumeratorException exc;

  _Numerator_query_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class NumeratorClient : virtual public NumeratorIf {
 public:
  NumeratorClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  NumeratorClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  void send_ping();
  void recv_ping();
  void query(Query& _return, const Query& request);
  void send_query(const Query& request);
  void recv_query(Query& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class NumeratorProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<NumeratorIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (NumeratorProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_query(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  NumeratorProcessor(boost::shared_ptr<NumeratorIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &NumeratorProcessor::process_ping;
    processMap_["query"] = &NumeratorProcessor::process_query;
  }

  virtual ~NumeratorProcessor() {}
};

class NumeratorProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  NumeratorProcessorFactory(const ::boost::shared_ptr< NumeratorIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< NumeratorIfFactory > handlerFactory_;
};

class NumeratorMultiface : virtual public NumeratorIf {
 public:
  NumeratorMultiface(std::vector<boost::shared_ptr<NumeratorIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~NumeratorMultiface() {}
 protected:
  std::vector<boost::shared_ptr<NumeratorIf> > ifaces_;
  NumeratorMultiface() {}
  void add(boost::shared_ptr<NumeratorIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    ifaces_[i]->ping();
  }

  void query(Query& _return, const Query& request) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->query(_return, request);
    }
    ifaces_[i]->query(_return, request);
    return;
  }

};

} // namespace

#endif
