/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "numerator_constants.h"

namespace numerator {

const numeratorConstants g_numerator_constants;

numeratorConstants::numeratorConstants() {
}

} // namespace

